name: CI workflow

on:
  push: 
    branches:
      - main
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim

    steps:
      - name: Checkout
        users: actions/checkout@v3

      - name: Install dependencies
        run: |
          # upgrade pip
          python -m pip install --upgrade pip
          # install requirements packages
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          # code quality check for critical errors
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          # comprehensive code quality check with specific styles and rules
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics
      
      - name: Run unit tests with nose
        run: |
          nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
